MaxEventSize: 0 # value 0 unlimit the maximum event size that can be sent to message bus or core-data

Writable:
  LogLevel: DEBUG

# uncomment when running from command-line in hybrid mode with -cp -o flags
#Registry:
# Host: localhost
#
#Clients:
# core-metadata:
#   Host: localhost

Service:
  Host: localhost
  Port: 59902
  StartupMsg: device lora started

MessageBus:
#  Host: localhost # uncomment when running from command-line in hybrid mode
  Optional:
    ClientId: device-lora

Device:
  # These have common values (currently), but must be here for service local env overrides to apply when customized
  ProfilesDir: "./res/profiles"
  DevicesDir: "./res/devices"

ChirpStack:
  Version: V3
  Host: 172.16.65.160:8080
  Username: admin
  Password: admin
  ActivateKey: bc67cd6eb45a08d975050b1887b93c23
