name: edgex-device-rest
base: core22
type: app
license: Apache-2.0
summary: EdgeX REST Device Service
description: Refer to https://snapcraft.io/edgex-device-rest
adopt-info: device-rest

# 1: edinburgh
# 2: fuji
# 3: geneva, hanoi
# 4: ireland, jakarta, kamakura, levski
# 5: minnesota
epoch: 5

# TODO: add armhf here when that's supported
architectures:
  - build-on: arm64
  - build-on: amd64

grade: stable
confinement: strict

slots:
  edgex-secretstore-token:
    interface: content
    source:
      write: [$SNAP_DATA/device-rest]
plugs:
  device-rest-config:
    interface: content
    target: $SNAP_DATA/config/device-rest

apps:
  device-rest:
    command: bin/device-rest --configDir $SNAP_DATA/config/device-rest/res --configProvider --registry
    command-chain:
       - bin/source-env-file.sh
    daemon: simple
    install-mode: disable
    environment:
      DEVICE_PROFILESDIR: "$SNAP_DATA/config/device-rest/res/profiles"
      DEVICE_DEVICESDIR: "$SNAP_DATA/config/device-rest/res/devices"
      SECRETSTORE_TOKENFILE: $SNAP_DATA/device-rest/secrets-token.json
    plugs: [network, network-bind]

parts:
  helper-go:
    source: snap/local/helper-go
    plugin: make
    build-snaps:
      - go/1.20/stable
    override-build: |
      cd $CRAFT_PART_SRC
      make build
      install -DT ./helper-go $CRAFT_PART_INSTALL/bin/helper-go

  device-rest:
    source: .
    plugin: make
    build-packages: 
      - git
    build-snaps:
      - go/1.20/stable
    override-build: |
      cd $CRAFT_PART_SRC

      if git describe ; then
        VERSION=$(git describe --tags --abbrev=0 | sed 's/v//')
      else
        VERSION="0.0.0"
      fi
      # set the version of the snap
      craftctl set version=$VERSION

      # write version to file for the build
      echo $VERSION > VERSION

      make build
      install -DT "./cmd/device-rest" "$CRAFT_PART_INSTALL/bin/device-rest"

      RES=$CRAFT_PART_INSTALL/config/device-rest/res/
      mkdir -p $RES
      cp -r cmd/res/* $RES
      
      DOC=$CRAFT_PART_INSTALL/usr/share/doc/device-rest
      mkdir -p $DOC
      cp Attribution.txt $DOC/Attribution.txt
      cp LICENSE $DOC/LICENSE

  local-bin:
    plugin: dump
    source: snap/local/bin
    organize:
      source-env-file.sh: bin/source-env-file.sh

      
